package com.example.model;

import jakarta.annotation.Generated;
import java.util.Date;

/**
 * Database Table Remarks:
 *   訂單
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order
 */
public class Order {
    /**
     * Database Column Remarks:
     *   交易序號
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0737753+08:00", comments="Source field: order.transaction_id")
    private String transactionId;

    /**
     * Database Column Remarks:
     *   訂購人
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0817909+08:00", comments="Source field: order.order_name")
    private String orderName;

    /**
     * Database Column Remarks:
     *   訂購電話
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0827884+08:00", comments="Source field: order.order_tel")
    private String orderTel;

    /**
     * Database Column Remarks:
     *   備註
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.083782+08:00", comments="Source field: order.customer_memo")
    private String customerMemo;

    /**
     * Database Column Remarks:
     *   狀態 A:審查中 C:已確認  E:結案
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.083782+08:00", comments="Source field: order.status")
    private String status;

    /**
     * Database Column Remarks:
     *   總金額
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0847858+08:00", comments="Source field: order.total")
    private Integer total;

    /**
     * Database Column Remarks:
     *   訂金
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0857859+08:00", comments="Source field: order.deposit")
    private Integer deposit;

    /**
     * Database Column Remarks:
     *   訂購日期
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0857859+08:00", comments="Source field: order.create_date")
    private Date createDate;

    /**
     * Database Column Remarks:
     *   預期取貨日期
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0867864+08:00", comments="Source field: order.pickup_date")
    private Date pickupDate;

    /**
     * Database Column Remarks:
     *   結案日期
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0867864+08:00", comments="Source field: order.close_date")
    private Date closeDate;

    /**
     * Database Column Remarks:
     *   南部蛋黃肉粽數量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0877902+08:00", comments="Source field: order.item_a_count")
    private Integer itemACount;

    /**
     * Database Column Remarks:
     *   南部粽數量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0877902+08:00", comments="Source field: order.item_b_count")
    private Integer itemBCount;

    /**
     * Database Column Remarks:
     *   北部肉粽數量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_c_count")
    private Integer itemCCount;

    /**
     * Database Column Remarks:
     *   白米豆沙數量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_d_count")
    private Integer itemDCount;

    /**
     * Database Column Remarks:
     *   溫度:H:熱 C:冷凍 N:都行
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0897864+08:00", comments="Source field: order.temperature")
    private String temperature;

    /**
     * Database Column Remarks:
     *   處理備註
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0897864+08:00", comments="Source field: order.apply_memo")
    private String applyMemo;

    /**
     * Database Column Remarks:
     *   紅豆鹼粽
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0907831+08:00", comments="Source field: order.item_e_count")
    private Integer itemECount;

    /**
     * Database Column Remarks:
     *   原味鹼粽
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0907831+08:00", comments="Source field: order.item_f_count")
    private Integer itemFCount;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0789083+08:00", comments="Source field: order.transaction_id")
    public String getTransactionId() {
        return transactionId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0817909+08:00", comments="Source field: order.transaction_id")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0817909+08:00", comments="Source field: order.order_name")
    public String getOrderName() {
        return orderName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0827884+08:00", comments="Source field: order.order_name")
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0827884+08:00", comments="Source field: order.order_tel")
    public String getOrderTel() {
        return orderTel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0827884+08:00", comments="Source field: order.order_tel")
    public void setOrderTel(String orderTel) {
        this.orderTel = orderTel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.083782+08:00", comments="Source field: order.customer_memo")
    public String getCustomerMemo() {
        return customerMemo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.083782+08:00", comments="Source field: order.customer_memo")
    public void setCustomerMemo(String customerMemo) {
        this.customerMemo = customerMemo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0847858+08:00", comments="Source field: order.status")
    public String getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0847858+08:00", comments="Source field: order.status")
    public void setStatus(String status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0847858+08:00", comments="Source field: order.total")
    public Integer getTotal() {
        return total;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0847858+08:00", comments="Source field: order.total")
    public void setTotal(Integer total) {
        this.total = total;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0857859+08:00", comments="Source field: order.deposit")
    public Integer getDeposit() {
        return deposit;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0857859+08:00", comments="Source field: order.deposit")
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0857859+08:00", comments="Source field: order.create_date")
    public Date getCreateDate() {
        return createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0867864+08:00", comments="Source field: order.create_date")
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0867864+08:00", comments="Source field: order.pickup_date")
    public Date getPickupDate() {
        return pickupDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0867864+08:00", comments="Source field: order.pickup_date")
    public void setPickupDate(Date pickupDate) {
        this.pickupDate = pickupDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0867864+08:00", comments="Source field: order.close_date")
    public Date getCloseDate() {
        return closeDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0877902+08:00", comments="Source field: order.close_date")
    public void setCloseDate(Date closeDate) {
        this.closeDate = closeDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0877902+08:00", comments="Source field: order.item_a_count")
    public Integer getItemACount() {
        return itemACount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0877902+08:00", comments="Source field: order.item_a_count")
    public void setItemACount(Integer itemACount) {
        this.itemACount = itemACount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0877902+08:00", comments="Source field: order.item_b_count")
    public Integer getItemBCount() {
        return itemBCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_b_count")
    public void setItemBCount(Integer itemBCount) {
        this.itemBCount = itemBCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_c_count")
    public Integer getItemCCount() {
        return itemCCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_c_count")
    public void setItemCCount(Integer itemCCount) {
        this.itemCCount = itemCCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_d_count")
    public Integer getItemDCount() {
        return itemDCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0887904+08:00", comments="Source field: order.item_d_count")
    public void setItemDCount(Integer itemDCount) {
        this.itemDCount = itemDCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0897864+08:00", comments="Source field: order.temperature")
    public String getTemperature() {
        return temperature;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0897864+08:00", comments="Source field: order.temperature")
    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0897864+08:00", comments="Source field: order.apply_memo")
    public String getApplyMemo() {
        return applyMemo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0897864+08:00", comments="Source field: order.apply_memo")
    public void setApplyMemo(String applyMemo) {
        this.applyMemo = applyMemo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0907831+08:00", comments="Source field: order.item_e_count")
    public Integer getItemECount() {
        return itemECount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0907831+08:00", comments="Source field: order.item_e_count")
    public void setItemECount(Integer itemECount) {
        this.itemECount = itemECount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0907831+08:00", comments="Source field: order.item_f_count")
    public Integer getItemFCount() {
        return itemFCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-12T18:13:47.0907831+08:00", comments="Source field: order.item_f_count")
    public void setItemFCount(Integer itemFCount) {
        this.itemFCount = itemFCount;
    }
}