package org.h800570023.order.model;

import jakarta.annotation.Generated;

/**
 * Database Table Remarks:
 *   line用戶資料
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table line_user
 */
public class LineUser {
    /**
     * Database Column Remarks:
     *   line帳號
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-18T20:30:30.571796+08:00", comments="Source field: line_user.id")
    private String id;

    /**
     * Database Column Remarks:
     *   是否通知N:否 Y:是
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-18T20:30:30.572685+08:00", comments="Source field: line_user.is_notify")
    private String isNotify;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-18T20:30:30.57248+08:00", comments="Source field: line_user.id")
    public String getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-18T20:30:30.572649+08:00", comments="Source field: line_user.id")
    public void setId(String id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-18T20:30:30.572729+08:00", comments="Source field: line_user.is_notify")
    public String getIsNotify() {
        return isNotify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2024-06-18T20:30:30.572779+08:00", comments="Source field: line_user.is_notify")
    public void setIsNotify(String isNotify) {
        this.isNotify = isNotify;
    }
}